### ISSUE TITLE
Transparent Child Window

### ISSUE THREAD

**Issue by wiless** [BurntSushi/xgbutil#33]
How do I create a transparent child window ?

This is how I create a child window under a root window
```
win, err := xwindow.Generate(xu)
win.Create(parent, X,Y, Width,Height, xproto.CwBackPixel, 0xfffff)
```
Is it something to do with the valuemasks  `xproto.CwBackPixel` ? 

Any pointer will be very helpful. Thanks.

**Comment by BurntSushi** [comment]
You need to run a compositor to get a transparent window. It's totally out of scope for this package.

**Comment by onodera-punpun** [comment]
I have a question related to this issue, I made Wingo accept png images (that get converted to xpm or whatever with xwindow) as window decorations, I want to use this to get a rounded corner effect, however, the alpha pixels show up as black instead of transparent, and yes, I am running a compositor. Do you know what causes this?

**Comment by BurntSushi** [comment]
@onodera-punpun Sorry, I don't. I wouldn't necessarily count on the transparency in png to translate to the X image format in such a way that a compositor would handle it correctly.
