### ISSUE TITLE
WTFPL not supported by go.dev / no LICENSE file

### ISSUE THREAD

**Issue by AlbinoGeek** [BurntSushi/xgbutil#54]
[Go.dev](https://pkg.go.dev/github.com/BurntSushi/xgbutil) will not show documentation for this library because there is no LICENSE file and the WTFPL is not in their supported list.

Perhaps you wish to use the [Unlicense](https://opensource.org/licenses/Unlicense)?

You can find more information on this issue [here](https://pkg.go.dev/license-policy).

**Comment by BurntSushi** [comment]
>  because there is no LICENSE file

Yes there is. It's called `COPYING` and it's a standard idiom. And your link literally says this idiom is supported.

> the WTFPL is not in their supported list

Oh well. Sorry. But I'm not playing this game again. I'm done relicensing things because of Google. If you want to see xgbutil's docs, then use a local godoc instance. Or use godoc.org until that is taken down.
